version: '3.7'

services:
  santicolle-apache:
    image: santicolle-apache-image:p4
    build: 
      context: ./P4-santicolle-apache
      dockerfile: DockerFileApacheP4
    cap_add:
      - NET_ADMIN
    user: root
    restart: always
    hostname: servidor-web

  web1:
    image: santicolle-apache-image:p4
    volumes:
      - ./P4-santicolle-apache/web_santicolle:/var/www/html/
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "8081:80"
      - "9081:443"
    networks:
      red_web:
        ipv4_address: 192.168.10.2
      red_servicios:
        ipv4_address: 192.168.20.2
    hostname: servidor-web-1
    
  web2:
    image: santicolle-apache-image:p4
    volumes:
      - ./P4-santicolle-apache/web_santicolle:/var/www/html/
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "8082:80"
      - "9082:443"
    networks:
      red_web:
        ipv4_address: 192.168.10.3
      red_servicios:
        ipv4_address: 192.168.20.3
    hostname: servidor-web-2
    
  web3:
    image: santicolle-apache-image:p4
    volumes:
      - ./P4-santicolle-apache/web_santicolle:/var/www/html/
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "8083:80"
      - "9083:443"
    networks:
      red_web:
        ipv4_address: 192.168.10.4
      red_servicios:
        ipv4_address: 192.168.20.4
    hostname: servidor-web-3
    
  web4:
    image: santicolle-apache-image:p4
    volumes:
      - ./P4-santicolle-apache/web_santicolle:/var/www/html/
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "8084:80"
      - "9084:443"
    networks:
      red_web:
        ipv4_address: 192.168.10.5
      red_servicios:
        ipv4_address: 192.168.20.5
    hostname: servidor-web-4
    
  web5:
    image: santicolle-apache-image:p4
    volumes:
      - ./P4-santicolle-apache/web_santicolle:/var/www/html/
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "8085:80"
      - "9085:443"
    networks:
      red_web:
        ipv4_address: 192.168.10.6
      red_servicios:
        ipv4_address: 192.168.20.6
    hostname: servidor-web-5
    
  web6:
    image: santicolle-apache-image:p4
    volumes:
      - ./P4-santicolle-apache/web_santicolle:/var/www/html/
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "8086:80"
      - "9086:443"
    networks:
      red_web:
        ipv4_address: 192.168.10.7
      red_servicios:
        ipv4_address: 192.168.20.7
    hostname: servidor-web-6
    
  web7:
    image: santicolle-apache-image:p4
    volumes:
      - ./P4-santicolle-apache/web_santicolle:/var/www/html/
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "8087:80"
      - "9087:443"
    networks:
      red_web:
        ipv4_address: 192.168.10.8
      red_servicios:
        ipv4_address: 192.168.20.8
    hostname: servidor-web-7
    
  web8:
    image: santicolle-apache-image:p4
    volumes:
      - ./P4-santicolle-apache/web_santicolle:/var/www/html/
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "8088:80"
      - "9088:443"
    networks:
      red_web:
        ipv4_address: 192.168.10.9
      red_servicios:
        ipv4_address: 192.168.20.9
    hostname: servidor-web-8
    
  balanceador-nginx-ssl:
    build:
      context: ./P4-santicolle-nginx
      dockerfile: DockerFileNginxP4
    image: santicolle-nginx-image:p4
    container_name: nginx
    ports:
      - "443:443"
    restart: always
    cap_add:
      - NET_ADMIN
    networks:
      red_web:
        ipv4_address: 192.168.10.50
    depends_on:
      - web1
      - web2
      - web3
      - web4
      - web5
      - web6
      - web7
      - web8

networks:
  red_web:
    external: true
    # ipam:
    #   config:
    #     - subnet: 192.168.10.0/24
  red_servicios:
    external: true
    # ipam:
    #   config:
    #     - subnet: 192.168.20.0/24