version: '3.7'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - 8080:80
      # - 8443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yml:/traefik.yml:ro
      - ./data/acme.json:/acme.json
      - ./data/configurations:/configurations
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.service=api@internal"
      # - "traefik.enable=true"
      # - "traefik.docker.network=proxy"
      # - "traefik.http.routers.traefik-secure.rule=Host(traefik.localhost)"
      # - "traefik.http.routers.traefik-secure.middlewares=user-auth@file"
      # - "traefik.http.routers.traefik-secure.service=api@internal"
      # - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      # - "traefik.http.routers.traefik-secure.tls.certresolver=letsencrypt"

  santicolle-apache:
    image: santicolle-apache-image:p2
    volumes:
      - ./web_santicolle:/var/www/html/
    build: 
      context: .
      dockerfile: DockerfileApache_santicolle_p2
    cap_add:
      - NET_ADMIN
    user: root
    hostname: servidor-web

  web1:
    image: santicolle-apache-image:p2
    volumes:
      - ./web_santicolle:/var/www/html/
    networks:
      red_web:
        ipv4_address: 192.168.10.2
      red_servicios:
        ipv4_address: 192.168.20.2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web1.rule=Host(`web.localhost`)"
      - "traefik.http.routers.web1.entrypoints=web"
      - "traefik.http.services.web1.loadbalancer.server.port=80"

  web2:
    image: santicolle-apache-image:p2
    volumes:
      - ./web_santicolle:/var/www/html/
    networks:
      red_web:
        ipv4_address: 192.168.10.3
      red_servicios:
        ipv4_address: 192.168.20.3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web2.rule=Host(`web.localhost`)"
      - "traefik.http.routers.web2.entrypoints=web"
      - "traefik.http.services.web2.loadbalancer.server.port=80"

  # Resto de servicios web...

networks:
  red_web:
    ipam:
      config:
        - subnet: 192.168.10.0/24
  red_servicios:
    ipam:
      config:
        - subnet: 192.168.20.0/24
  proxy:
    ipam:
      config:
        - subnet: 192.168.30.0/24